name: DunWar
version: '${version}'
main: io.github.dun1998.dunwar.DunWar
api-version: '1.20'
authors: [dun198]
depend: [WorldGuard,WorldEdit]
commands:
  Teams:
    description: 'Lists all teams'
    usage: /<command>
  CreateTeam:
    description: 'Creates a team with the specified color'
    usage: /<command> <color>
  RenameTeam:
    description: 'Renames a team.'
    usage: /<command> <current name||color> <new name>
  JoinTeam:
    description: 'Join either a random or specific team'
    usage: /<command> <optional Team Name>
  Team:
    description: 'View the team info'
    usage: /<command> <optional Team Name>
  SetMap:
    description: 'Sets the game map'
    usage: /<command> <radius>
  CreateControlLand:
    description: 'Creates a new control land.'
    usage: /<command> <name>
  StartGame:
    description: 'Starts the game.'
    usage: /<command>
  GetControlLands:
    description: 'Lists control lands.'
    usage: /<command>
  AddControlPoint:
    description: 'Adds a control point to a control land.'
    usage: /<command> <control land> <name>
  StopGame:
    description: 'Stops a running game.'
    usage: /<command>
  SetTeamBase:
    description: 'Sets a teams base.'
    usage: /<command> <team name>
  SetTeamSpawn:
    description: 'Sets a teams spawn at the players current location.'
    usage: /<command> <team name>
